# First stage: Build App
FROM maven:sapmachine AS build

# Set working directory in container
WORKDIR /app

# Copy app files
COPY . .

# Build the application

RUN mvn package

# Second stage: Run App
FROM eclipse-temurin:17-jre-alpine

# Set working directory in container
WORKDIR /app

# Copy JAR file from build stage

COPY --from=build /app/target/demo-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

# Run the application
CMD ["java", "-jar", "app.jar"]

