# Use Python base image
FROM python:3.9-slim

# Set working directory
WORKDIR /app

# Copy all files
COPY . .

# Install required packages
RUN pip install -r requirements.txt

# Expose port 5000
EXPOSE 5000

# Run the frontend application
CMD ["python", "app.py"]

