# Use Python base image
FROM python:3.9

# Set working directory
WORKDIR /app

# Copy app files
COPY . .

# Install Flask
RUN pip install flask

# Set environment variables (for production build)
ENV APP_MODE=defualt
ENV APP_REGION=unkwon

# Expose port 8080
EXPOSE 8080

# Run the app
CMD ["python", "app.py"]

