---
- name: Configure MySQL DB
  hosts: dev
  become: true
  vars_files:
    - secrets.yaml

  tasks:
    - name: Install MySQL and Python MySQL library
      apt:
        name:
          - mysql-server
          - python3-mysqldb
        state: present

    - name: Start MySQL service
      service:
        name: mysql
        state: started

    - name: Create MySQL user
      mysql_user:
        name: amr
        password: "{{ database_password }}"
        host: localhost
        priv: "*.*:ALL,GRANT"  
        state: present

    - name: Create MySQL database 'ivolve'
      mysql_db:
        name: ivolve
        state: present
        login_user: root
        login_unix_socket: /var/run/mysqld/mysqld.sock  

